# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(548, 556)
        Dialog.setStyleSheet(" background-color: #906bff")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(170, 10, 341, 431))
        self.frame.setStyleSheet("font-size:15pt;")
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.input_x1 = QtWidgets.QLineEdit(self.frame)
        self.input_x1.setStyleSheet("border: 5px solid #b38dd9;\n"
"color:black;\n"
"font-weight: bold;\n"
"font-size:15pt;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.input_x1.setAlignment(QtCore.Qt.AlignCenter)
        self.input_x1.setObjectName("input_x1")
        self.verticalLayout_2.addWidget(self.input_x1)
        self.input_x2 = QtWidgets.QLineEdit(self.frame)
        self.input_x2.setStyleSheet("border: 5px solid #b38dd9;\n"
"color:black;\n"
"font-weight: bold;\n"
"font-size:15pt;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.input_x2.setAlignment(QtCore.Qt.AlignCenter)
        self.input_x2.setObjectName("input_x2")
        self.verticalLayout_2.addWidget(self.input_x2)
        self.delta = QtWidgets.QLineEdit(self.frame)
        self.delta.setStyleSheet("border: 5px solid #b38dd9;\n"
"color:black;\n"
"font-weight: bold;\n"
"font-size:15pt;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.delta.setAlignment(QtCore.Qt.AlignCenter)
        self.delta.setObjectName("delta")
        self.verticalLayout_2.addWidget(self.delta)
        self.E = QtWidgets.QLineEdit(self.frame)
        self.E.setStyleSheet("border: 5px solid #b38dd9;\n"
"color:black;\n"
"font-weight: bold;\n"
"font-size:15pt;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.E.setAlignment(QtCore.Qt.AlignCenter)
        self.E.setObjectName("E")
        self.verticalLayout_2.addWidget(self.E)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(190, 470, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:pressed{    \n"
"    background-color:#906bff;\n"
"}\n"
"\n"
"QPushButton{\n"
"border: 5px solid #b38dd9;\n"
"background-color: rgba(255, 255, 255, 30);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.frame1 = QtWidgets.QFrame(Dialog)
        self.frame1.setGeometry(QtCore.QRect(30, 50, 121, 371))
        self.frame1.setStyleSheet("")
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 5px solid #b38dd9;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 5px solid #b38dd9;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 5px solid #b38dd9;\n"
"background-color: rgba(255, 255, 255, 30);\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame1)
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 5px solid #b38dd9;\n"
"background-color: rgba(255, 255, 255, 30);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Введите данные"))
        self.pushButton.setText(_translate("Dialog", "Отправить"))
        self.label.setText(_translate("Dialog", "Введите X1"))
        self.label_2.setText(_translate("Dialog", "Введите X2"))
        self.label_3.setText(_translate("Dialog", "Введите\n"
"Delta X"))
        self.label_4.setText(_translate("Dialog", "Введите E"))